<link rel="stylesheet" href="templates/admin/vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="templates/admin/vendor/fonts/circular-std/style.css">
<link rel="stylesheet" href="templates/admin/libs/css/style.css">
<link rel="stylesheet" href="templates/admin/vendor/fonts/fontawesome/css/fontawesome-all.css">
<link rel="stylesheet" href="templates/admin/vendor/charts/chartist-bundle/chartist.css">
<link rel="stylesheet" href="templates/admin/vendor/charts/morris-bundle/morris.css">
<link rel="stylesheet" href="templates/admin/vendor/fonts/material-design-iconic-font/css/materialdesignicons.min.css">
<link rel="stylesheet" href="templates/admin/vendor/charts/c3charts/c3.css">
<link rel="stylesheet" href="templates/admin/vendor/fonts/flag-icon-css/flag-icon.min.css">